// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/pivotal-cf-experimental/routing-api/authentication"
)

type FakeToken struct {
	DecodeTokenStub        func(userToken string) error
	decodeTokenMutex       sync.RWMutex
	decodeTokenArgsForCall []struct {
		userToken string
	}
	decodeTokenReturns struct {
		result1 error
	}
}

func (fake *FakeToken) DecodeToken(userToken string) error {
	fake.decodeTokenMutex.Lock()
	fake.decodeTokenArgsForCall = append(fake.decodeTokenArgsForCall, struct {
		userToken string
	}{userToken})
	fake.decodeTokenMutex.Unlock()
	if fake.DecodeTokenStub != nil {
		return fake.DecodeTokenStub(userToken)
	} else {
		return fake.decodeTokenReturns.result1
	}
}

func (fake *FakeToken) DecodeTokenCallCount() int {
	fake.decodeTokenMutex.RLock()
	defer fake.decodeTokenMutex.RUnlock()
	return len(fake.decodeTokenArgsForCall)
}

func (fake *FakeToken) DecodeTokenArgsForCall(i int) string {
	fake.decodeTokenMutex.RLock()
	defer fake.decodeTokenMutex.RUnlock()
	return fake.decodeTokenArgsForCall[i].userToken
}

func (fake *FakeToken) DecodeTokenReturns(result1 error) {
	fake.DecodeTokenStub = nil
	fake.decodeTokenReturns = struct {
		result1 error
	}{result1}
}

var _ authentication.Token = new(FakeToken)
