// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/pivotal-cf-experimental/routing-api/db"
	"github.com/pivotal-cf-experimental/routing-api/handlers"
)

type FakeRouteValidator struct {
	ValidateCreateStub        func(routes []db.Route, maxTTL int) *handlers.Error
	validateCreateMutex       sync.RWMutex
	validateCreateArgsForCall []struct {
		routes []db.Route
		maxTTL int
	}
	validateCreateReturns struct {
		result1 *handlers.Error
	}
	ValidateDeleteStub        func(routes []db.Route) *handlers.Error
	validateDeleteMutex       sync.RWMutex
	validateDeleteArgsForCall []struct {
		routes []db.Route
	}
	validateDeleteReturns struct {
		result1 *handlers.Error
	}
}

func (fake *FakeRouteValidator) ValidateCreate(routes []db.Route, maxTTL int) *handlers.Error {
	fake.validateCreateMutex.Lock()
	fake.validateCreateArgsForCall = append(fake.validateCreateArgsForCall, struct {
		routes []db.Route
		maxTTL int
	}{routes, maxTTL})
	fake.validateCreateMutex.Unlock()
	if fake.ValidateCreateStub != nil {
		return fake.ValidateCreateStub(routes, maxTTL)
	} else {
		return fake.validateCreateReturns.result1
	}
}

func (fake *FakeRouteValidator) ValidateCreateCallCount() int {
	fake.validateCreateMutex.RLock()
	defer fake.validateCreateMutex.RUnlock()
	return len(fake.validateCreateArgsForCall)
}

func (fake *FakeRouteValidator) ValidateCreateArgsForCall(i int) ([]db.Route, int) {
	fake.validateCreateMutex.RLock()
	defer fake.validateCreateMutex.RUnlock()
	return fake.validateCreateArgsForCall[i].routes, fake.validateCreateArgsForCall[i].maxTTL
}

func (fake *FakeRouteValidator) ValidateCreateReturns(result1 *handlers.Error) {
	fake.ValidateCreateStub = nil
	fake.validateCreateReturns = struct {
		result1 *handlers.Error
	}{result1}
}

func (fake *FakeRouteValidator) ValidateDelete(routes []db.Route) *handlers.Error {
	fake.validateDeleteMutex.Lock()
	fake.validateDeleteArgsForCall = append(fake.validateDeleteArgsForCall, struct {
		routes []db.Route
	}{routes})
	fake.validateDeleteMutex.Unlock()
	if fake.ValidateDeleteStub != nil {
		return fake.ValidateDeleteStub(routes)
	} else {
		return fake.validateDeleteReturns.result1
	}
}

func (fake *FakeRouteValidator) ValidateDeleteCallCount() int {
	fake.validateDeleteMutex.RLock()
	defer fake.validateDeleteMutex.RUnlock()
	return len(fake.validateDeleteArgsForCall)
}

func (fake *FakeRouteValidator) ValidateDeleteArgsForCall(i int) []db.Route {
	fake.validateDeleteMutex.RLock()
	defer fake.validateDeleteMutex.RUnlock()
	return fake.validateDeleteArgsForCall[i].routes
}

func (fake *FakeRouteValidator) ValidateDeleteReturns(result1 *handlers.Error) {
	fake.ValidateDeleteStub = nil
	fake.validateDeleteReturns = struct {
		result1 *handlers.Error
	}{result1}
}

var _ handlers.RouteValidator = new(FakeRouteValidator)
